//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: game.proto
namespace gprotocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserLost")]
  public partial class UserLost : global::ProtoBuf.IExtensible
  {
    public UserLost() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private string _u_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"u_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string u_name
    {
      get { return _u_name; }
      set { _u_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRes")]
  public partial class LoginRes : global::ProtoBuf.IExtensible
  {
    public LoginRes() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRoomList")]
  public partial class GetRoomList : global::ProtoBuf.IExtensible
  {
    public GetRoomList() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomItem")]
  public partial class RoomItem : global::ProtoBuf.IExtensible
  {
    public RoomItem() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomList")]
  public partial class RoomList : global::ProtoBuf.IExtensible
  {
    public RoomList() {}
    
    private readonly global::System.Collections.Generic.List<RoomItem> _room_list = new global::System.Collections.Generic.List<RoomItem>();
    [global::ProtoBuf.ProtoMember(1, Name=@"room_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RoomItem> room_list
    {
      get { return _room_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoom")]
  public partial class CreateRoom : global::ProtoBuf.IExtensible
  {
    public CreateRoom() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoomRes")]
  public partial class CreateRoomRes : global::ProtoBuf.IExtensible
  {
    public CreateRoomRes() {}
    
    private int _seat_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_id
    {
      get { return _seat_id; }
      set { _seat_id = value; }
    }
    private int _room_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherPlayerEnter")]
  public partial class OtherPlayerEnter : global::ProtoBuf.IExtensible
  {
    public OtherPlayerEnter() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _seat_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"seat_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_id
    {
      get { return _seat_id; }
      set { _seat_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherPlayerExit")]
  public partial class OtherPlayerExit : global::ProtoBuf.IExtensible
  {
    public OtherPlayerExit() {}
    
    private int _seat_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_id
    {
      get { return _seat_id; }
      set { _seat_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterRoom")]
  public partial class EnterRoom : global::ProtoBuf.IExtensible
  {
    public EnterRoom() {}
    
    private int _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterRoomRes")]
  public partial class EnterRoomRes : global::ProtoBuf.IExtensible
  {
    public EnterRoomRes() {}
    
    private int _seat_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_id
    {
      get { return _seat_id; }
      set { _seat_id = value; }
    }
    private int _room_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExitRoom")]
  public partial class ExitRoom : global::ProtoBuf.IExtensible
  {
    public ExitRoom() {}
    
    private int _seat_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_id
    {
      get { return _seat_id; }
      set { _seat_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChessInfo")]
  public partial class ChessInfo : global::ProtoBuf.IExtensible
  {
    public ChessInfo() {}
    
    private string _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private int _chess;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"chess", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chess
    {
      get { return _chess; }
      set { _chess = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Ready")]
  public partial class Ready : global::ProtoBuf.IExtensible
  {
    public Ready() {}
    
    private readonly global::System.Collections.Generic.List<ChessInfo> _chess_info = new global::System.Collections.Generic.List<ChessInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"chess_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ChessInfo> chess_info
    {
      get { return _chess_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameStart")]
  public partial class GameStart : global::ProtoBuf.IExtensible
  {
    public GameStart() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherPlayerReady")]
  public partial class OtherPlayerReady : global::ProtoBuf.IExtensible
  {
    public OtherPlayerReady() {}
    
    private int _seat_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_id
    {
      get { return _seat_id; }
      set { _seat_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CouldMov")]
  public partial class CouldMov : global::ProtoBuf.IExtensible
  {
    public CouldMov() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Path")]
  public partial class Path : global::ProtoBuf.IExtensible
  {
    public Path() {}
    
    private string _pt;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pt
    {
      get { return _pt; }
      set { _pt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MovResReq")]
  public partial class MovResReq : global::ProtoBuf.IExtensible
  {
    public MovResReq() {}
    
    private string _start;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string start
    {
      get { return _start; }
      set { _start = value; }
    }
    private string _targetpos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"targetpos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string targetpos
    {
      get { return _targetpos; }
      set { _targetpos = value; }
    }
    private readonly global::System.Collections.Generic.List<Path> _path = new global::System.Collections.Generic.List<Path>();
    [global::ProtoBuf.ProtoMember(3, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Path> path
    {
      get { return _path; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MovResReturn")]
  public partial class MovResReturn : global::ProtoBuf.IExtensible
  {
    public MovResReturn() {}
    
    private string _start;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string start
    {
      get { return _start; }
      set { _start = value; }
    }
    private string _targetpos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"targetpos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string targetpos
    {
      get { return _targetpos; }
      set { _targetpos = value; }
    }
    private int _res;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int res
    {
      get { return _res; }
      set { _res = value; }
    }
    private readonly global::System.Collections.Generic.List<Path> _path = new global::System.Collections.Generic.List<Path>();
    [global::ProtoBuf.ProtoMember(4, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Path> path
    {
      get { return _path; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerFailed")]
  public partial class PlayerFailed : global::ProtoBuf.IExtensible
  {
    public PlayerFailed() {}
    
    private int _seat_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_id
    {
      get { return _seat_id; }
      set { _seat_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameOver")]
  public partial class GameOver : global::ProtoBuf.IExtensible
  {
    public GameOver() {}
    
    private int _winner1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"winner1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int winner1
    {
      get { return _winner1; }
      set { _winner1 = value; }
    }
    private int _winner2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"winner2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int winner2
    {
      get { return _winner2; }
      set { _winner2 = value; }
    }
    private int _loser1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"loser1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int loser1
    {
      get { return _loser1; }
      set { _loser1 = value; }
    }
    private int _loser2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"loser2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int loser2
    {
      get { return _loser2; }
      set { _loser2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Stype")]
    public enum Stype
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_STYPE", Value=0)]
      INVALID_STYPE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"game_server", Value=1)]
      game_server = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Cmd")]
    public enum Cmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_VAULE", Value=0)]
      INVALID_VAULE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eUserLost", Value=1)]
      eUserLost = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eLoginReq", Value=2)]
      eLoginReq = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eLoginRes", Value=3)]
      eLoginRes = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eGetRoomList", Value=4)]
      eGetRoomList = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eRoomList", Value=5)]
      eRoomList = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eCreateRoom", Value=6)]
      eCreateRoom = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eCreateRoomRes", Value=7)]
      eCreateRoomRes = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eOtherPlayerEnter", Value=8)]
      eOtherPlayerEnter = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eOtherPlayerExit", Value=9)]
      eOtherPlayerExit = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eEnterRoom", Value=10)]
      eEnterRoom = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eEnterRoomRes", Value=11)]
      eEnterRoomRes = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eExitRoom", Value=12)]
      eExitRoom = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eReady", Value=13)]
      eReady = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eGameStart", Value=14)]
      eGameStart = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eOtherPlayerReady", Value=15)]
      eOtherPlayerReady = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eCouldMov", Value=16)]
      eCouldMov = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eMovResReq", Value=17)]
      eMovResReq = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eMovResReturn", Value=18)]
      eMovResReturn = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ePlayerFailed", Value=19)]
      ePlayerFailed = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eGameOver", Value=20)]
      eGameOver = 20
    }
  
}